apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive
  namespace: drive
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drive
  template:
    metadata:
      labels:
        name: drive
    spec:
      containers:
        - name: drive
          image: us-west1-docker.pkg.dev/techacceleration-platform-dev/drive/drive-web:development
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/mnt/certs/"
            name: gdemo-ssl
            readOnly: true
          ports:
            - containerPort: 443
      imagePullSecrets:
        - name: pullsecret
      volumes:
        - name: gdemo-ssl
          secret:
            secretName: gdemo-ssl

---

apiVersion: v1
kind: Service
metadata:
  name: drive
  namespace: drive
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    name: drive

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drive
  namespace: drive
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - drive.demo.genesys.com
    secretName: gdemo-ssl
  rules:
  - host: drive.demo.genesys.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: drive
            port: 
              number: 443